name: merkle-tree-ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain from file
        id: nightly-toolchain
        run: echo "::set-output name=version::$(cat resources/rust-toolchain.in)"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.nightly-toolchain.outputs.version }}
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - run: make prepare
      # Needed for gcc install
      - run: sudo apt update && sudo apt install -y build-essential
      - uses: Swatinem/rust-cache@v2
      - name: "Check linting"
        run: make check-lint
      # Tests will be added after NCTL interaction is possible.
      - name: "Tests"
        run: make test
      - name: "Build"
        run: make build
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

    name: Code Coverage Summary Report
    uses: irongut/CodeCoverageSummary@v1.3.0
    with:
      filename: cobertura.xml
      badge: true
      fail_below_min: true
      format: markdown
      hide_branch_rate: false
      hide_complexity: true
      indicators: true
      output: both
      thresholds: "60 80"
